name: pdf_buddy
description: "A Flutter web-based PDF editor application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^2.32.0
  flutter_dotenv: ^5.1.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # PDF Handling
  syncfusion_flutter_pdf: ^29.1.39
  syncfusion_flutter_pdfviewer: ^29.1.39
  
  # File Upload and Browser Integration
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  
  # Image Processing
  image: ^4.1.7
  
  # UI Components
  google_fonts: ^6.1.0
  flutter_adaptive_scaffold: ^0.3.2
  font_awesome_flutter: ^10.8.0
  device_info_plus: ^11.3.3
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
